// ============================================================
// 烁林煊系统真实案例合集 - 案例数据文件
// ============================================================
// 使用说明：
//   1. 添加新案例：在对应板块的 items 数组中新增一条 { img, caption }
//   2. 删除案例：直接删除对应的对象行
//   3. 修改标题：修改 caption 字段的内容即可
//   4. 修改图片：修改 img 字段的路径
//   5. 调整顺序：案例按优先级自动排列，调整数组顺序即可改变展示顺序
//   6. 每行一个案例，方便用文本编辑器批量替换
// ============================================================

window.caseData = {
  "身体调理": {"items": [
    {"img": "images/身体调理/3 通技术前后的效果.png", "caption": "3 通技术前后的效果"},
    {"img": "images/身体调理/三通技术前后对比.jpg", "caption": "三通技术前后对比"},
    {"img": "images/身体调理/三通技术前后对比.png", "caption": "三通技术前后对比"},
    {"img": "images/身体调理/三通焕颜技术前后对比.jpg", "caption": "三通焕颜技术前后对比"},
    {"img": "images/身体调理/中医三通焕颜技术前后对比.jpg", "caption": "中医三通焕颜技术前后对比"},
    {"img": "images/身体调理/减肥前后对比.jpg", "caption": "体态管理前后对比"},
    {"img": "images/身体调理/客户减肥数据变化.jpg", "caption": "客户体态管理数据变化"},
    {"img": "images/身体调理/客户排毒前后对比.jpg", "caption": "客户身体养护前后对比"},
    {"img": "images/身体调理/客户调理减肥数据变化.jpg", "caption": "客户改善体态管理数据变化"},
    {"img": "images/身体调理/焕颜技术前后对比.jpg", "caption": "焕颜技术前后对比"},
    {"img": "images/身体调理/调理痘痘脸第一天第二天效果对比.jpg", "caption": "改善皮肤困扰脸第一天第二天效果对比"},
    {"img": "images/身体调理/三通技术 40 天的效果.png", "caption": "三通技术 40 天的效果"},
    {"img": "images/身体调理/三通焕颜技术前后.jpg", "caption": "三通焕颜技术前后"},
    {"img": "images/身体调理/三通焕颜技术前后的改变.jpg", "caption": "三通焕颜技术前后的改变"},
    {"img": "images/身体调理/中医三通焕颜技术前后.jpg", "caption": "中医三通焕颜技术前后"},
    {"img": "images/身体调理/客户减肥数据.jpg", "caption": "客户体态管理数据"},
    {"img": "images/身体调理/焕颜技术前后.jpg", "caption": "焕颜技术前后"},
    {"img": "images/身体调理/科学减肥 1 个月的效果.jpg", "caption": "科学体态管理 1 个月的效果"},
    {"img": "images/身体调理/系统调理 12 天的效果.jpg", "caption": "系统改善 12 天的效果"},
    {"img": "images/身体调理/系统调理 3 个月的变化.jpg", "caption": "系统改善 3 个月的变化"},
    {"img": "images/身体调理/系统调理20 天的变化.jpg", "caption": "系统改善20 天的变化"},
    {"img": "images/身体调理/调理子宫肌瘤案例-医院检查数据.jpg", "caption": "改善身体困扰案例-医院检查数据"},
    {"img": "images/身体调理/调理富贵包 1 次的效果.jpg", "caption": "改善颈部困扰 1 次的效果"},
    {"img": "images/身体调理/调理富贵包 3 个月的效果.jpg", "caption": "改善颈部困扰 3 个月的效果"},
    {"img": "images/身体调理/调理激素脸 16 天的效果.jpg", "caption": "改善皮肤困扰 16 天的效果"},
    {"img": "images/身体调理/调理激素脸 2 个月的效果.png", "caption": "改善皮肤困扰 2 个月的效果"},
    {"img": "images/身体调理/调理激素脸 3 天的效果.jpg", "caption": "改善皮肤困扰 3 天的效果"},
    {"img": "images/身体调理/调理静脉曲张 1 次的效果.jpg", "caption": "改善腿部困扰 1 次的效果"},
    {"img": "images/身体调理/三通技术一次的效果.jpg", "caption": "三通技术一次的效果"},
    {"img": "images/身体调理/三通技术调理激素脸效果.jpg", "caption": "三通技术改善皮肤困扰效果"},
    {"img": "images/身体调理/三通焕颜技术前-后效果.jpg", "caption": "三通焕颜技术前-后效果"},
    {"img": "images/身体调理/中医三通技术淡斑效果.png", "caption": "中医三通技术肤色改善效果"},
    {"img": "images/身体调理/修复痘痘肌效果.jpg", "caption": "修复皮肤困扰肌效果"},
    {"img": "images/身体调理/做三通技术一次的效果.jpg", "caption": "做三通技术一次的效果"},
    {"img": "images/身体调理/焕颜技术 5 次的效果.jpg", "caption": "焕颜技术 5 次的效果"},
    {"img": "images/身体调理/科学减肥 1 个月瘦 15 斤.jpg", "caption": "科学体态管理 1 个月体态变化 15 斤"},
    {"img": "images/身体调理/科学减肥 2 个月瘦 22 斤.jpg", "caption": "科学体态管理 2 个月体态变化 22 斤"},
    {"img": "images/身体调理/科学减肥 2 个月瘦 40 斤.jpg", "caption": "科学体态管理 2 个月体态变化 40 斤"},
    {"img": "images/身体调理/系统调理 1 个月头发白转黑.jpg", "caption": "系统改善 1 个月头发发质改善"},
    {"img": "images/身体调理/调理 10 多年湿疹的效果.jpg", "caption": "改善 10 多年皮肤困扰的效果"},
    {"img": "images/身体调理/调理斑的效果.jpg", "caption": "肤色改善的效果"},
    {"img": "images/身体调理/调理激素脸效果.jpg", "caption": "改善皮肤困扰效果"},
    {"img": "images/身体调理/调理痘痘脸的效果.png", "caption": "改善皮肤困扰脸的效果"},
    {"img": "images/身体调理/调理白转黑的效果.jpg", "caption": "发质改善的效果"},
    {"img": "images/身体调理/调理皮肤红血丝的效果.jpg", "caption": "改善皮肤泛红困扰的效果"},
    {"img": "images/身体调理/调理面瘫效果.jpg", "caption": "改善面部困扰效果"},
    {"img": "images/身体调理/20 多年的湿疹调理好了.jpg", "caption": "20 多年的皮肤困扰改善了"},
    {"img": "images/身体调理/三通技术 2 次的皮肤状态.jpg", "caption": "三通技术 2 次的皮肤状态"},
    {"img": "images/身体调理/三通技术前-后.jpg", "caption": "三通技术前-后"},
    {"img": "images/身体调理/中医三通技术淡斑.png", "caption": "中医三通技术肤色改善"},
    {"img": "images/身体调理/养生与不养生的区别.jpg", "caption": "养生与不养生的区别"},
    {"img": "images/身体调理/头发白转黑.jpg", "caption": "头发发质改善"},
    {"img": "images/身体调理/调理便秘和减肥.jpg", "caption": "改善肠道舒适和体态管理"},
    {"img": "images/身体调理/调理多囊卵巢聊天 1.jpg", "caption": "改善身体困扰聊天 1"},
    {"img": "images/身体调理/调理多囊卵巢聊天 2.jpg", "caption": "改善身体困扰聊天 2"},
    {"img": "images/身体调理/调理多囊卵巢聊天-聊天记录.jpg", "caption": "改善身体困扰聊天-聊天记录"},
    {"img": "images/身体调理/调理头皮癣（1）.jpg", "caption": "改善头部皮肤困扰（1）"},
    {"img": "images/身体调理/调理头皮癣（2）.jpg", "caption": "改善头部皮肤困扰（2）"},
    {"img": "images/身体调理/调理好卵巢囊肿.jpg", "caption": "改善身体困扰"},
    {"img": "images/身体调理/调理子宫肌瘤案例-微信聊天记录.jpg", "caption": "改善身体困扰案例-微信聊天记录"},
    {"img": "images/身体调理/调理总胆红素.jpg", "caption": "改善健康指标"},
    {"img": "images/身体调理/调理斑.jpg", "caption": "肤色改善"},
    {"img": "images/身体调理/调理眼睛（1）.jpg", "caption": "改善眼睛（1）"},
    {"img": "images/身体调理/调理眼睛（2）.jpg", "caption": "改善眼睛（2）"},
    {"img": "images/身体调理/调理眼睛（3）.jpg", "caption": "改善眼睛（3）"},
    {"img": "images/身体调理/调理糖尿病.jpg", "caption": "改善代谢困扰"},
    {"img": "images/身体调理/调理肾结石-结石具体尺寸.jpg", "caption": "改善身体困扰-结石具体尺寸"},
    {"img": "images/身体调理/调理肾结石-聊天记录.jpg", "caption": "改善身体困扰-聊天记录"},
    {"img": "images/身体调理/调理背部脓包.jpg", "caption": "改善背部困扰"},
    {"img": "images/身体调理/调理解决 20 多年的湿疹.jpg", "caption": "改善解决 20 多年的皮肤困扰"},
    {"img": "images/身体调理/调理黄气.jpg", "caption": "肤色改善"}
  ]},
  "分店主": {"items": [
    {"img": "images/分店主/客户付 3000 签轻创业.jpg", "caption": "客户付 3000 签轻创业"},
    {"img": "images/分店主/充卡 1000 + 签轻创业.jpg", "caption": "充卡 1000 + 签轻创业"},
    {"img": "images/分店主/在持续签轻创业.jpg", "caption": "在持续签轻创业"},
    {"img": "images/分店主/客户付 1.84w 调理身体.jpg", "caption": "客户付 1.84w 改善身体"},
    {"img": "images/分店主/客户付 1.8w 调理身体.jpg", "caption": "客户付 1.8w 改善身体"},
    {"img": "images/分店主/客户付 1980 三通技术卡.jpg", "caption": "客户付 1980 三通技术卡"},
    {"img": "images/分店主/客户付 1w 调理身体.jpg", "caption": "客户付 1w 改善身体"},
    {"img": "images/分店主/客户付 2.5w 调理身体.jpg", "caption": "客户付 2.5w 改善身体"},
    {"img": "images/分店主/客户付 2.7k 调理身体.jpg", "caption": "客户付 2.7k 改善身体"},
    {"img": "images/分店主/客户付 5k 调理身体.jpg", "caption": "客户付 5k 改善身体"},
    {"img": "images/分店主/客户付 6.9k 调理身体.jpg", "caption": "客户付 6.9k 改善身体"},
    {"img": "images/分店主/客户付 6000 调理身体.jpg", "caption": "客户付 6000 改善身体"},
    {"img": "images/分店主/客户付 7k 调理身体.jpg", "caption": "客户付 7k 改善身体"},
    {"img": "images/分店主/客户付费 1.1w 调理身体.jpg", "caption": "客户付费 1.1w 改善身体"},
    {"img": "images/分店主/客户付费 4k 调理身体.jpg", "caption": "客户付费 4k 改善身体"},
    {"img": "images/分店主/客户拿现金签轻创业.jpg", "caption": "客户拿现金签轻创业"},
    {"img": "images/分店主/签轻创业.jpg", "caption": "签轻创业"},
    {"img": "images/分店主/调理身体+签轻创业.jpg", "caption": "改善身体+签轻创业"},
    {"img": "images/分店主/充 1k 汗蒸卡.jpg", "caption": "充 1k 汗蒸卡"},
    {"img": "images/分店主/充卡 1000.jpg", "caption": "充卡 1000"},
    {"img": "images/分店主/加入开店（1）.jpg", "caption": "加入开店（1）"},
    {"img": "images/分店主/加入开店（2）.jpg", "caption": "加入开店（2）"},
    {"img": "images/分店主/客户充卡 2000.jpg", "caption": "客户充卡 2000"},
    {"img": "images/分店主/拿现金充经络卡.jpg", "caption": "拿现金充经络卡"},
    {"img": "images/分店主/2 个月瘦 31 斤.jpg", "caption": "2 个月体态变化 31 斤"},
    {"img": "images/分店主/客户 1980 调理身体.jpg", "caption": "客户 1980 改善身体"},
    {"img": "images/分店主/客户办 3980 套餐卡.jpg", "caption": "客户办 3980 套餐卡"}
  ]},
  "轻创业": {"items": [
    {"img": "images/轻创业/客户付 4980 调理身体.jpg", "caption": "客户付 4980 改善身体"},
    {"img": "images/轻创业/客户付 9.6k 调理身体.jpg", "caption": "客户付 9.6k 改善身体"},
    {"img": "images/轻创业/客户付费 1.5w 调理身体.JPG", "caption": "客户付费 1.5w 改善身体"},
    {"img": "images/轻创业/轻创业的客户付 6k 调理身体.JPG", "caption": "轻创业的客户付 6k 改善身体"},
    {"img": "images/轻创业/轻创业的客户付费 1.8w 调理身体.JPG", "caption": "轻创业的客户付费 1.8w 改善身体"},
    {"img": "images/轻创业/充1000 元汗蒸卡.jpg", "caption": "充1000 元汗蒸卡"},
    {"img": "images/轻创业/加入 2 个轻创业.JPG", "caption": "加入 2 个轻创业"},
    {"img": "images/轻创业/轻创业客户充 1000 元汗蒸卡.JPG", "caption": "轻创业客户充 1000 元汗蒸卡"},
    {"img": "images/轻创业/轻创业的客户充 1000 元的卡.JPG", "caption": "轻创业的客户充 1000 元的卡"},
    {"img": "images/轻创业/轻创业的客户转介绍.JPG", "caption": "轻创业的客户转介绍"}
  ]},
  "操盘手": {"items": [
    {"img": "images/操盘手/加入操盘手第 13 天变现.JPG", "caption": "加入操盘手第 13 天变现"},
    {"img": "images/操盘手/0 基础操盘手第 13 天变现.JPG", "caption": "0 基础操盘手第 13 天变现"},
    {"img": "images/操盘手/23 号操盘手4天变现 1.1w.jpg", "caption": "23 号操盘手4天变现 1.1w"},
    {"img": "images/操盘手/0 基础线上获客操盘手直接变现.JPG", "caption": "0 基础线上获客操盘手直接变现"},
    {"img": "images/操盘手/8 号操盘手变现（10）.JPG", "caption": "8 号操盘手变现（10）"},
    {"img": "images/操盘手/8 号操盘手变现（1）.JPG", "caption": "8 号操盘手变现（1）"},
    {"img": "images/操盘手/8 号操盘手变现（2）.JPG", "caption": "8 号操盘手变现（2）"},
    {"img": "images/操盘手/8 号操盘手变现（3）.JPG", "caption": "8 号操盘手变现（3）"},
    {"img": "images/操盘手/8 号操盘手变现（4）.JPG", "caption": "8 号操盘手变现（4）"},
    {"img": "images/操盘手/8 号操盘手变现（5）.JPG", "caption": "8 号操盘手变现（5）"},
    {"img": "images/操盘手/8 号操盘手变现（6）.JPG", "caption": "8 号操盘手变现（6）"},
    {"img": "images/操盘手/8 号操盘手变现（7）.JPG", "caption": "8 号操盘手变现（7）"},
    {"img": "images/操盘手/8 号操盘手变现（8）.JPG", "caption": "8 号操盘手变现（8）"},
    {"img": "images/操盘手/8 号操盘手变现（9）.JPG", "caption": "8 号操盘手变现（9）"},
    {"img": "images/操盘手/操盘手做线上获客额外变现.JPG", "caption": "操盘手做线上获客额外变现"},
    {"img": "images/操盘手/操盘手变现 2094 元+2.JPG", "caption": "操盘手变现 2094 元+2"},
    {"img": "images/操盘手/操盘手变现 2094 元.JPG", "caption": "操盘手变现 2094 元"},
    {"img": "images/操盘手/操盘手变现+10.JPG", "caption": "操盘手变现+10"},
    {"img": "images/操盘手/操盘手变现+11.JPG", "caption": "操盘手变现+11"},
    {"img": "images/操盘手/操盘手的客户付费闭门分享会.JPG", "caption": "操盘手的客户付费闭门分享会"},
    {"img": "images/操盘手/操盘手的客户付费闭门分享会（1）.PNG", "caption": "操盘手的客户付费闭门分享会（1）"},
    {"img": "images/操盘手/操盘手的客户付费闭门分享会（2）.PNG", "caption": "操盘手的客户付费闭门分享会（2）"},
    {"img": "images/操盘手/操盘手的海外客户付费.JPG", "caption": "操盘手的海外客户付费"},
    {"img": "images/操盘手/操盘手轻松赚钱.JPG", "caption": "操盘手轻松赚钱"},
    {"img": "images/操盘手/精准客户直接变现.JPG", "caption": "精准客户直接变现"},
    {"img": "images/操盘手/线上获客操盘手变现 2094 月.JPG", "caption": "线上获客操盘手变现 2094 月"},
    {"img": "images/操盘手/线上获客操盘手变现 2240 元.JPG", "caption": "线上获客操盘手变现 2240 元"},
    {"img": "images/操盘手/线上获客操盘手变现 3000.JPG", "caption": "线上获客操盘手变现 3000"},
    {"img": "images/操盘手/线上获客操盘手回本.JPG", "caption": "线上获客操盘手回本"},
    {"img": "images/操盘手/线上获客操盘手持续变现.JPG", "caption": "线上获客操盘手持续变现"},
    {"img": "images/操盘手/线上获客操盘手收入 2240 元.JPG", "caption": "线上获客操盘手收入 2240 元"},
    {"img": "images/操盘手/线上获客操盘手收益 2094 元.JPG", "caption": "线上获客操盘手收益 2094 元"},
    {"img": "images/操盘手/线上获客操盘手获得 2094 元分润.JPG", "caption": "线上获客操盘手获得 2094 元分润"},
    {"img": "images/操盘手/线上获客操盘手获得 2240 元分润.JPG", "caption": "线上获客操盘手获得 2240 元分润"},
    {"img": "images/操盘手/线上获客操盘手获得分润.JPG", "caption": "线上获客操盘手获得分润"},
    {"img": "images/操盘手/客户加入操盘手业务.jpg", "caption": "客户加入操盘手业务"},
    {"img": "images/操盘手/客户报名操盘手（1）.JPG", "caption": "客户报名操盘手（1）"},
    {"img": "images/操盘手/客户报名操盘手（2）.JPG", "caption": "客户报名操盘手（2）"},
    {"img": "images/操盘手/客户报名操盘手（3）.JPG", "caption": "客户报名操盘手（3）"},
    {"img": "images/操盘手/操盘手来的客户直接报名闭门分享会.JPG", "caption": "操盘手来的客户直接报名闭门分享会"},
    {"img": "images/操盘手/操盘手来的客户直接报名闭门分享会（2）.JPG", "caption": "操盘手来的客户直接报名闭门分享会（2）"},
    {"img": "images/操盘手/操盘手的客户直接报名闭门分享会.JPG", "caption": "操盘手的客户直接报名闭门分享会"},
    {"img": "images/操盘手/线上客户报名线下课.jpg", "caption": "线上客户报名线下课"},
    {"img": "images/操盘手/线上获客日常加微信数据（10）.JPG", "caption": "线上获客日常加微信数据（10）"},
    {"img": "images/操盘手/线上获客日常加微信数据（11）.JPG", "caption": "线上获客日常加微信数据（11）"},
    {"img": "images/操盘手/线上获客日常加微信数据（12）.JPG", "caption": "线上获客日常加微信数据（12）"},
    {"img": "images/操盘手/线上获客日常加微信数据（13）.JPG", "caption": "线上获客日常加微信数据（13）"},
    {"img": "images/操盘手/线上获客日常加微信数据（14）.JPG", "caption": "线上获客日常加微信数据（14）"},
    {"img": "images/操盘手/线上获客日常加微信数据（15）.JPG", "caption": "线上获客日常加微信数据（15）"},
    {"img": "images/操盘手/线上获客日常加微信数据（16）.JPG", "caption": "线上获客日常加微信数据（16）"},
    {"img": "images/操盘手/线上获客日常加微信数据（1）.JPG", "caption": "线上获客日常加微信数据（1）"},
    {"img": "images/操盘手/线上获客日常加微信数据（2）.JPG", "caption": "线上获客日常加微信数据（2）"},
    {"img": "images/操盘手/线上获客日常加微信数据（3）.JPG", "caption": "线上获客日常加微信数据（3）"},
    {"img": "images/操盘手/线上获客日常加微信数据（4）.JPG", "caption": "线上获客日常加微信数据（4）"},
    {"img": "images/操盘手/线上获客日常加微信数据（5）.JPG", "caption": "线上获客日常加微信数据（5）"},
    {"img": "images/操盘手/线上获客日常加微信数据（6）.JPG", "caption": "线上获客日常加微信数据（6）"},
    {"img": "images/操盘手/线上获客日常加微信数据（7）.JPG", "caption": "线上获客日常加微信数据（7）"},
    {"img": "images/操盘手/线上获客日常加微信数据（8）.JPG", "caption": "线上获客日常加微信数据（8）"},
    {"img": "images/操盘手/线上获客日常加微信数据（9）.JPG", "caption": "线上获客日常加微信数据（9）"},
    {"img": "images/操盘手/0 基础操盘手第 7 天就把客户加到微信.JPG", "caption": "0 基础操盘手第 7 天就把客户加到微信"},
    {"img": "images/操盘手/日更公众号第 9 天来客户.jpg", "caption": "日更公众号第 9 天来客户"},
    {"img": "images/操盘手/公众号违规.png", "caption": "公众号违规"},
    {"img": "images/操盘手/操盘手在持续来客户.PNG", "caption": "操盘手在持续来客户"},
    {"img": "images/操盘手/操盘手对后端很放心.JPG", "caption": "操盘手对后端很放心"},
    {"img": "images/操盘手/操盘手的客户来线下系统调理身体.JPG", "caption": "操盘手的客户来线下系统改善身体"},
    {"img": "images/操盘手/操盘手的客户来线下调理身体.JPG", "caption": "操盘手的客户来线下改善身体"},
    {"img": "images/操盘手/操盘手说：线上引流小 case.jpg", "caption": "操盘手说：线上引流小 case"},
    {"img": "images/操盘手/督促操盘手按时完成任务（1）.JPG", "caption": "督促操盘手按时完成任务（1）"},
    {"img": "images/操盘手/督促操盘手按时完成任务（2）.JPG", "caption": "督促操盘手按时完成任务（2）"},
    {"img": "images/操盘手/线上来的客户直接喷水费.JPG", "caption": "线上来的客户直接喷水费"}
  ]}
};

// 各板块统计信息
const caseStats = {
  "身体调理": { "count": 71, "label": "调理改善客户" },
  "分店主": { "count": 27, "label": "连锁分店" },
  "轻创业": { "count": 10, "label": "轻创业者" },
  "操盘手": { "count": 70, "label": "线上获客操盘手" }
};